repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.18.2
    hooks:
      - id: pyupgrade
        args: ["--py36-plus"]

  - repo: https://github.com/psf/black
    rev: 21.5b1
    hooks:
      - id: black
        args: ["--target-version", "py36"]
        # override until resolved: https://github.com/psf/black/issues/402
        files: \.pyi?$
        types: []

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies: [flake8-2020, flake8-implicit-str-concat]

  - repo: https://github.com/PyCQA/isort
    rev: 5.8.0
    hooks:
      - id: isort

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.8.0
    hooks:
      - id: python-check-blanket-noqa

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
