language: python

cache:
  pip: true
  directories:
    - "$HOME/.npm"
    - "$HOME/.nvm"

python:
 - 3.6
 - 3.7
 - 3.8
 - 3.9

before_install:
  - nvm install 14

install:
 - pip install flake8
 - pip install -r requirements.txt
 - pip install -r history-requirements.txt
 - npm install svgexport -g

script:
 # Unit tests
 - python test_utils.py

 # Static analysis
 - flake8

 # Test run
 - ./build.sh

 # History charts
 - git config remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
 - git fetch origin
 - python history_get.py -n 10
 - python history_plot.py

matrix:
  fast_finish: true
